export interface PermissionFamily {
  previousKey: string;
  family: string;
  nameAr: string;
  nameEn: string;
  group: string;
  read: string;
  create: string;
  update: string;
  delete: string;
  clientScope: boolean;
  highTrust: boolean;
}

export const MANAGEMENT_PERMISSION_FAMILIES: PermissionFamily[] = [
  {
    previousKey: "roles.manage",
    family: "roles",
    nameAr: "الأدوار والصلاحيات",
    nameEn: "Roles",
    group: "Security",
    read: "roles.read",
    create: "roles.create",
    update: "roles.update",
    delete: "roles.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "permissions.manage",
    family: "permissions",
    nameAr: "الصلاحيات المباشرة",
    nameEn: "Permissions",
    group: "Security",
    read: "permissions.read",
    create: "permissions.create",
    update: "permissions.update",
    delete: "permissions.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "support_access.manage",
    family: "support_access",
    nameAr: "وصول الدعم الفني",
    nameEn: "Support Access",
    group: "Security",
    read: "support_access.read",
    create: "support_access.create",
    update: "support_access.update",
    delete: "support_access.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "company_profile.manage",
    family: "company_profile",
    nameAr: "ملف وبيانات الشركة",
    nameEn: "Company Profile",
    group: "Catalog",
    read: "company_profile.read",
    create: "company_profile.create",
    update: "company_profile.update",
    delete: "company_profile.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "operating_cities.manage",
    family: "operating_cities",
    nameAr: "مدن التشغيل",
    nameEn: "Operating Cities",
    group: "Catalog",
    read: "operating_cities.read",
    create: "operating_cities.create",
    update: "operating_cities.update",
    delete: "operating_cities.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "tags.manage",
    family: "tags",
    nameAr: "الوسوم والتصنيفات",
    nameEn: "Tags",
    group: "Catalog",
    read: "tags.read",
    create: "tags.create",
    update: "tags.update",
    delete: "tags.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "riders.manage",
    family: "riders",
    nameAr: "المناديب",
    nameEn: "Delegates / Riders",
    group: "Workforce",
    read: "riders.read",
    create: "riders.create",
    update: "riders.update",
    delete: "riders.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "sponsors.manage",
    family: "sponsors",
    nameAr: "الكفلاء",
    nameEn: "Sponsors",
    group: "Workforce",
    read: "sponsors.read",
    create: "sponsors.create",
    update: "sponsors.update",
    delete: "sponsors.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "residency.manage",
    family: "residency",
    nameAr: "الإقامات",
    nameEn: "Residency",
    group: "Compliance",
    read: "residency.read",
    create: "residency.create",
    update: "residency.update",
    delete: "residency.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "licenses.manage",
    family: "licenses",
    nameAr: "رخص القيادة",
    nameEn: "Driver Licenses",
    group: "Compliance",
    read: "licenses.read",
    create: "licenses.create",
    update: "licenses.update",
    delete: "licenses.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "rider_cards.manage",
    family: "rider_cards",
    nameAr: "بطاقات المناديب",
    nameEn: "Rider Cards",
    group: "Compliance",
    read: "rider_cards.read",
    create: "rider_cards.create",
    update: "rider_cards.update",
    delete: "rider_cards.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "health_cards.manage",
    family: "health_cards",
    nameAr: "البطاقات الصحية",
    nameEn: "Health Cards",
    group: "Compliance",
    read: "health_cards.read",
    create: "health_cards.create",
    update: "health_cards.update",
    delete: "health_cards.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "insurance.manage",
    family: "insurance",
    nameAr: "وثائق التأمين",
    nameEn: "Insurance",
    group: "Compliance",
    read: "insurance.read",
    create: "insurance.create",
    update: "insurance.update",
    delete: "insurance.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "promissory_notes.manage",
    family: "promissory_notes",
    nameAr: "سندات الأمر",
    nameEn: "Promissory Notes",
    group: "Compliance",
    read: "promissory_notes.read",
    create: "promissory_notes.create",
    update: "promissory_notes.update",
    delete: "promissory_notes.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "documents.catalog.manage",
    family: "documents.catalog",
    nameAr: "دليل الوثائق",
    nameEn: "Document Catalog",
    group: "Documents",
    read: "documents.catalog.read",
    create: "documents.catalog.create",
    update: "documents.catalog.update",
    delete: "documents.catalog.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "platform_accounts.manage",
    family: "platform_accounts",
    nameAr: "حسابات وعقود المنصات",
    nameEn: "Platform Accounts",
    group: "Operations",
    read: "platform_accounts.read",
    create: "platform_accounts.create",
    update: "platform_accounts.update",
    delete: "platform_accounts.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "platform_assignments.manage",
    family: "platform_assignments",
    nameAr: "تعيينات المنصات",
    nameEn: "Platform Assignments",
    group: "Operations",
    read: "platform_assignments.read",
    create: "platform_assignments.create",
    update: "platform_assignments.update",
    delete: "platform_assignments.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "housing.manage",
    family: "housing",
    nameAr: "السكن والمستودعات والمرافق",
    nameEn: "Housing",
    group: "Operations",
    read: "housing.read",
    create: "housing.create",
    update: "housing.update",
    delete: "housing.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "phone_sims.manage",
    family: "phone_sims",
    nameAr: "شرائح الاتصال SIM",
    nameEn: "Phone SIMs",
    group: "Operations",
    read: "phone_sims.read",
    create: "phone_sims.create",
    update: "phone_sims.update",
    delete: "phone_sims.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "notifications.manage",
    family: "notifications",
    nameAr: "الإشعارات",
    nameEn: "Notifications",
    group: "Reporting",
    read: "notifications.read",
    create: "notifications.create",
    update: "notifications.update",
    delete: "notifications.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "fleet.vehicles.manage",
    family: "fleet.vehicles",
    nameAr: "المركبات والأسطول",
    nameEn: "Fleet Vehicles",
    group: "Fleet",
    read: "fleet.vehicles.read",
    create: "fleet.vehicles.create",
    update: "fleet.vehicles.update",
    delete: "fleet.vehicles.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "fleet.assignments.manage",
    family: "fleet.assignments",
    nameAr: "تعيينات وعهد المركبات",
    nameEn: "Vehicle Assignments",
    group: "Fleet",
    read: "fleet.assignments.read",
    create: "fleet.assignments.create",
    update: "fleet.assignments.update",
    delete: "fleet.assignments.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "fleet.issues.manage",
    family: "fleet.issues",
    nameAr: "أعطال وبلاغات الأسطول",
    nameEn: "Fleet Issues",
    group: "Fleet",
    read: "fleet.issues.read",
    create: "fleet.issues.create",
    update: "fleet.issues.update",
    delete: "fleet.issues.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "fleet.compliance.manage",
    family: "fleet.compliance",
    nameAr: "تراخيص وتأمين الأسطول",
    nameEn: "Fleet Compliance",
    group: "Fleet",
    read: "fleet.compliance.read",
    create: "fleet.compliance.create",
    update: "fleet.compliance.update",
    delete: "fleet.compliance.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "fleet.corrections.manage",
    family: "fleet.corrections",
    nameAr: "تصحيحات الأسطول والعداد",
    nameEn: "Fleet Corrections",
    group: "Fleet",
    read: "fleet.corrections.read",
    create: "fleet.corrections.create",
    update: "fleet.corrections.update",
    delete: "fleet.corrections.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "fleet.registration_transitions.manage",
    family: "fleet.registration_transitions",
    nameAr: "تحويل تسجيل المركبات (نقل عام)",
    nameEn: "Registration Transitions",
    group: "Fleet",
    read: "fleet.registration_transitions.read",
    create: "fleet.registration_transitions.create",
    update: "fleet.registration_transitions.update",
    delete: "fleet.registration_transitions.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "fleet.daily_distances.manage",
    family: "fleet.daily_distances",
    nameAr: "المسافات اليومية للأسطول",
    nameEn: "Fleet Daily Distances",
    group: "Fleet",
    read: "fleet.daily_distances.read",
    create: "fleet.daily_distances.create",
    update: "fleet.daily_distances.update",
    delete: "fleet.daily_distances.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "jahez.handovers.manage",
    family: "jahez.handovers",
    nameAr: "تسليم حسابات جاهز",
    nameEn: "Jahez Handovers",
    group: "Operations",
    read: "jahez.handovers.read",
    create: "jahez.handovers.create",
    update: "jahez.handovers.update",
    delete: "jahez.handovers.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "jahez.collections.manage",
    family: "jahez.collections",
    nameAr: "تحصيلات وتسويات جاهز",
    nameEn: "Jahez Collections",
    group: "Operations",
    read: "jahez.collections.read",
    create: "jahez.collections.create",
    update: "jahez.collections.update",
    delete: "jahez.collections.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "jahez.earnings.manage",
    family: "jahez.earnings",
    nameAr: "أرباح جاهز",
    nameEn: "Jahez Earnings",
    group: "Operations",
    read: "jahez.earnings.read",
    create: "jahez.earnings.create",
    update: "jahez.earnings.update",
    delete: "jahez.earnings.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "jahez.imports.manage",
    family: "jahez.imports",
    nameAr: "استيرادات ملفات جاهز",
    nameEn: "Jahez Imports",
    group: "Operations",
    read: "jahez.imports.read",
    create: "jahez.imports.create",
    update: "jahez.imports.update",
    delete: "jahez.imports.delete",
    clientScope: true,
    highTrust: false,
  },
  {
    previousKey: "jahez.adjustments.manage",
    family: "jahez.adjustments",
    nameAr: "قيود وتسويات جاهز المالية",
    nameEn: "Jahez Adjustments",
    group: "Operations",
    read: "jahez.adjustments.read",
    create: "jahez.adjustments.create",
    update: "jahez.adjustments.update",
    delete: "jahez.adjustments.delete",
    clientScope: true,
    highTrust: true,
  },
  {
    previousKey: "fuel.manage",
    family: "fuel",
    nameAr: "بطاقات واستخدام الوقود",
    nameEn: "Fuel Cards",
    group: "Fuel",
    read: "fuel.read",
    create: "fuel.create",
    update: "fuel.update",
    delete: "fuel.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "maintenance.locations.manage",
    family: "maintenance.locations",
    nameAr: "مواقع وورش الصيانة",
    nameEn: "Maintenance Locations",
    group: "Maintenance",
    read: "maintenance.locations.read",
    create: "maintenance.locations.create",
    update: "maintenance.locations.update",
    delete: "maintenance.locations.delete",
    clientScope: false,
    highTrust: true,
  },
  {
    previousKey: "maintenance.external_jobs.manage",
    family: "maintenance.external_jobs",
    nameAr: "أعمال الورش الخارجية",
    nameEn: "External Workshop Jobs",
    group: "Maintenance",
    read: "maintenance.external_jobs.read",
    create: "maintenance.external_jobs.create",
    update: "maintenance.external_jobs.update",
    delete: "maintenance.external_jobs.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "maintenance.part_sales.manage",
    family: "maintenance.part_sales",
    nameAr: "مبيعات قطع الغيار",
    nameEn: "Part Sales",
    group: "Maintenance",
    read: "maintenance.part_sales.read",
    create: "maintenance.part_sales.create",
    update: "maintenance.part_sales.update",
    delete: "maintenance.part_sales.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "maintenance.customer_labor_charges.manage",
    family: "maintenance.customer_labor_charges",
    nameAr: "أجور يد العملاء",
    nameEn: "Customer Labor Charges",
    group: "Maintenance",
    read: "maintenance.customer_labor_charges.read",
    create: "maintenance.customer_labor_charges.create",
    update: "maintenance.customer_labor_charges.update",
    delete: "maintenance.customer_labor_charges.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "maintenance.mechanic_labor_payments.manage",
    family: "maintenance.mechanic_labor_payments",
    nameAr: "مستحقات الميكانيكيين والفنيين",
    nameEn: "Mechanic Labor Payments",
    group: "Maintenance",
    read: "maintenance.mechanic_labor_payments.read",
    create: "maintenance.mechanic_labor_payments.create",
    update: "maintenance.mechanic_labor_payments.update",
    delete: "maintenance.mechanic_labor_payments.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "inventory.items.manage",
    family: "inventory.items",
    nameAr: "أصناف المخزون وقطع الغيار",
    nameEn: "Inventory Items",
    group: "Inventory",
    read: "inventory.items.read",
    create: "inventory.items.create",
    update: "inventory.items.update",
    delete: "inventory.items.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "inventory.receipts.manage",
    family: "inventory.receipts",
    nameAr: "فواتير واستلام المشتريات والموردين",
    nameEn: "Inventory Receipts",
    group: "Inventory",
    read: "inventory.receipts.read",
    create: "inventory.receipts.create",
    update: "inventory.receipts.update",
    delete: "inventory.receipts.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "inventory.returns.manage",
    family: "inventory.returns",
    nameAr: "مرتجع الموردين وصرف المناديب",
    nameEn: "Inventory Returns",
    group: "Inventory",
    read: "inventory.returns.read",
    create: "inventory.returns.create",
    update: "inventory.returns.update",
    delete: "inventory.returns.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "leave_requests.manage",
    family: "leave_requests",
    nameAr: "طلبات وأنواع ومسارات الإجازات",
    nameEn: "Leave Requests",
    group: "Workflows",
    read: "leave_requests.read",
    create: "leave_requests.create",
    update: "leave_requests.update",
    delete: "leave_requests.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "absence_cases.manage",
    family: "absence_cases",
    nameAr: "حالات وبلاغات الغياب",
    nameEn: "Absence Cases",
    group: "Workflows",
    read: "absence_cases.read",
    create: "absence_cases.create",
    update: "absence_cases.update",
    delete: "absence_cases.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "employee_status_changes.manage",
    family: "employee_status_changes",
    nameAr: "تغييرات حالة الموظف",
    nameEn: "Employee Status Changes",
    group: "Workflows",
    read: "employee_status_changes.read",
    create: "employee_status_changes.create",
    update: "employee_status_changes.update",
    delete: "employee_status_changes.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "legal_cases.manage",
    family: "legal_cases",
    nameAr: "القضايا والجلسات القانونية",
    nameEn: "Legal Cases",
    group: "Workforce",
    read: "legal_cases.read",
    create: "legal_cases.create",
    update: "legal_cases.update",
    delete: "legal_cases.delete",
    clientScope: false,
    highTrust: false,
  },
  {
    previousKey: "hr_forms.templates.manage",
    family: "hr_forms.templates",
    nameAr: "نماذج ومصمم الموارد البشرية",
    nameEn: "HR Form Templates",
    group: "HR forms",
    read: "hr_forms.templates.read",
    create: "hr_forms.templates.create",
    update: "hr_forms.templates.update",
    delete: "hr_forms.templates.delete",
    clientScope: false,
    highTrust: true,
  },
];

export const FAMILY_BY_PREFIX = new Map<string, PermissionFamily>(
  MANAGEMENT_PERMISSION_FAMILIES.map((f) => [f.family, f]),
);

export const ALL_FAMILY_KEYS = new Set<string>(
  MANAGEMENT_PERMISSION_FAMILIES.flatMap((f) => [f.read, f.create, f.update, f.delete]),
);

export function getFamilyForPermissionKey(key: string): { family: PermissionFamily; action: "read" | "create" | "update" | "delete" } | null {
  for (const f of MANAGEMENT_PERMISSION_FAMILIES) {
    if (key === f.read) return { family: f, action: "read" };
    if (key === f.create) return { family: f, action: "create" };
    if (key === f.update) return { family: f, action: "update" };
    if (key === f.delete) return { family: f, action: "delete" };
  }
  return null;
}
