"use client";
import type { FormEvent } from "react";
import { useEffect, useState } from "react";
import { BriefcaseBusiness, ContactRound, Save, UserRound, Bike } from "lucide-react";
import { hrCatalogApi, type HrRow } from "../../lib/hr/api";
import { listSponsors, type Sponsor } from "../../lib/workforce/api";
import { Button } from "../ui/Button";
import { Card } from "../ui/Card";
import { Input } from "../ui/Input";

const allFields = [
  ["iqamaNo","رقم الإقامة","text"],["residencyProfession","مهنة الإقامة","text"],["workingForMeAs","يعمل لدينا بوظيفة","text"],["fullNameAr","الاسم بالعربية","text"],["fullNameEn","الاسم بالإنجليزية","text"],["nationality","الجنسية","text"],["birthDate","تاريخ الميلاد","date"],["primaryPhone","الجوال","text"],["secondaryPhone","جوال إضافي","text"],["email","البريد الإلكتروني","email"],["emergencyContactName","اسم جهة اتصال الطوارئ","text"],["emergencyContactRelationship","صلة القرابة","text"],["emergencyContactPhone","جوال الطوارئ","text"],["statusReason","سبب الحالة","text"],["hireDate","تاريخ التعيين","date"],["contractStartDate","بداية العقد","date"],["contractEndDate","نهاية العقد","date"],["probationEndDate","نهاية التجربة","date"],["terminationDate","تاريخ الانتهاء","date"],["alternateContactName","اسم الاتصال البديل","text"],["alternateContactPhone","جوال الاتصال البديل","text"],
] as const;
type FieldKey=(typeof allFields)[number][0];
type Tab="basic"|"contact"|"work"|"rider";
const basic:FieldKey[]=["iqamaNo","fullNameAr","fullNameEn","nationality","birthDate"];
const contact:FieldKey[]=["primaryPhone","secondaryPhone","email","emergencyContactName","emergencyContactRelationship","emergencyContactPhone"];
const work:FieldKey[]=["statusReason","hireDate","terminationDate"];
const contract:FieldKey[]=["contractStartDate","contractEndDate","probationEndDate"];
const blank=(value:FormDataEntryValue|null)=>String(value??"").trim()||null;

export function EmployeeForm({initial,submitLabel,onSave}:{initial:Record<string,unknown>;submitLabel:string;onSave:(payload:Record<string,unknown>)=>Promise<void>}){
  const[isEmployee,setEmployee]=useState(initial.isEmployee===undefined?true:Boolean(initial.isEmployee));
  const[engagement,setEngagement]=useState(String(initial.engagementType??"SponsoredInternal"));
  const[active,setActive]=useState<Tab>("basic");
  const[saving,setSaving]=useState(false),[error,setError]=useState("");
  const[workTypes,setWorkTypes]=useState<HrRow[]>([]),[cities,setCities]=useState<HrRow[]>([]),[sponsors,setSponsors]=useState<Sponsor[]>([]),[professions,setProfessions]=useState<HrRow[]>([]),[jobTitles,setJobTitles]=useState<HrRow[]>([]),[catalogsLoading,setCatalogsLoading]=useState(true);
  useEffect(()=>{void Promise.all([hrCatalogApi.list("operational-work-types"),hrCatalogApi.list("operating-cities"),listSponsors(),hrCatalogApi.list("residency-professions"),hrCatalogApi.list("job-titles")]).then(([types,operatingCities,sponsorRows,professionRows,titleRows])=>{setWorkTypes(types);setCities(operatingCities);setSponsors(sponsorRows);setProfessions(professionRows);setJobTitles(titleRows)}).catch(()=>setError("تعذر تحميل القوائم المرجعية للنموذج.")).finally(()=>setCatalogsLoading(false))},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const payload:Record<string,unknown>={rowVersion:initial.rowVersion??null,rider:isEmployee?null:{tShirtSize:blank(form.get("tShirtSize")),operationalNotes:blank(form.get("operationalNotes")),rowVersion:initial.riderRowVersion??null}};allFields.forEach(([key])=>payload[key]=blank(form.get(key)));payload.isEmployee=isEmployee;payload.engagementType=engagement;payload.status=form.get("status");payload.gender=blank(form.get("gender"));payload.maritalStatus=blank(form.get("maritalStatus"));payload.notes=blank(form.get("notes"));payload.operationalWorkTypeId=blank(form.get("operationalWorkTypeId"));payload.operatingCityId=blank(form.get("operatingCityId"));payload.sponsorId=engagement==="SponsoredInternal"?blank(form.get("sponsorId")):null;setSaving(true);setError("");try{await onSave(payload)}catch{setError("تعذر حفظ البيانات. راجع الحقول المطلوبة والقيم المختارة.")}finally{setSaving(false)}}
  const tabs=[{key:"basic" as const,label:"البيانات الأساسية",icon:UserRound},{key:"contact" as const,label:"التواصل",icon:ContactRound},{key:"work" as const,label:"العمل والعلاقة",icon:BriefcaseBusiness},...(!isEmployee?[{key:"rider" as const,label:"بيانات المندوب",icon:Bike}]:[])];
  const renderFields=(keys:FieldKey[])=>keys.map(key=>{const field=allFields.find(item=>item[0]===key)!;return <Input key={key} name={key} label={field[1]} type={field[2]} required={key==="fullNameAr"} defaultValue={String(initial[key]??"")} dir={key==="email"||key.includes("Phone")||key==="iqamaNo"?"ltr":undefined}/>});
  const selectClass="h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 font-normal outline-none focus:border-[#1167c9] focus:ring-4 focus:ring-blue-100";
  return <form onSubmit={submit} className="space-y-5" dir="rtl"><Card className="overflow-hidden"><div className="border-b border-[var(--border)] p-3 sm:p-4"><div role="tablist" aria-label="أقسام بيانات الموظف" className="flex gap-2 overflow-x-auto">{tabs.map(tab=>{const Icon=tab.icon,selected=active===tab.key;return <button key={tab.key} type="button" role="tab" aria-selected={selected} onClick={()=>setActive(tab.key)} className={`inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-bold ${selected?"bg-[#1167c9] text-white":"border border-[var(--border)] text-[var(--muted)] hover:bg-blue-50"}`}><Icon size={17}/>{tab.label}</button>})}</div></div><div className="p-5 sm:p-7"><section role="tabpanel" hidden={active!=="basic"} className="grid gap-4 sm:grid-cols-2"><h2 className="col-span-full text-lg font-black">الهوية والبيانات الشخصية</h2>{renderFields(basic)}<CatalogSelect name="residencyProfession" label="مهنة الإقامة" value={initial.residencyProfession} loading={catalogsLoading} options={professions.map(item=>({value:String(item.nameAr??item.code),label:String(item.nameAr??item.code)}))}/><CatalogSelect name="workingForMeAs" label="يعمل لدينا بوظيفة" value={initial.workingForMeAs} loading={catalogsLoading} options={jobTitles.map(item=>({value:String(item.nameAr??item.code),label:String(item.nameAr??item.code)}))}/><Select label="الجنس" name="gender" value={initial.gender} options={[{value:"",label:"غير محدد"},{value:"Male",label:"ذكر"},{value:"Female",label:"أنثى"}]} className={selectClass}/><Select label="الحالة الاجتماعية" name="maritalStatus" value={initial.maritalStatus} options={[{value:"",label:"غير محددة"},{value:"Single",label:"أعزب"},{value:"Married",label:"متزوج"}]} className={selectClass}/></section>
  <section role="tabpanel" hidden={active!=="contact"} className="grid gap-4 sm:grid-cols-2"><h2 className="col-span-full text-lg font-black">بيانات التواصل والطوارئ</h2>{renderFields(contact)}{engagement==="OutsideRider"&&renderFields(["alternateContactName","alternateContactPhone"])}</section>
  <section role="tabpanel" hidden={active!=="work"} className="grid gap-4 sm:grid-cols-2"><h2 className="col-span-full text-lg font-black">العمل والعلاقة التشغيلية</h2><Select label="نوع الشخص" value={isEmployee?"employee":"rider"} onChange={value=>{setEmployee(value==="employee");if(value==="employee"&&active==="rider")setActive("work")}} required options={[{value:"employee",label:"موظف إداري"},{value:"rider",label:"مندوب"}]} className={selectClass}/><Select label="نوع الارتباط" name="engagementType" value={engagement} onChange={setEngagement} required options={[{value:"SponsoredInternal",label:"على كفالة الشركة"},{value:"OutsideRider",label:"مندوب خارجي"}]} className={selectClass}/><Select label="حالة الموظف" name="status" value={initial.status??"Draft"} required options={[{value:"Draft",label:"مسودة"},{value:"Onboarding",label:"قيد التهيئة"},{value:"Active",label:"نشط"},{value:"Suspended",label:"موقوف"},{value:"OnLeave",label:"في إجازة"},{value:"Terminated",label:"منتهي"}]} className={selectClass}/>{renderFields(work)}<CatalogSelect name="operationalWorkTypeId" label="نوع العمل التشغيلي" value={initial.operationalWorkTypeId} loading={catalogsLoading} options={workTypes.map(item=>({value:item.id,label:String(item.nameAr??item.code)}))}/><CatalogSelect name="operatingCityId" label="مدينة التشغيل" value={initial.operatingCityId} loading={catalogsLoading} options={cities.map(item=>({value:item.id,label:String(item.nameAr??item.code)}))}/>{engagement==="SponsoredInternal"&&<><CatalogSelect name="sponsorId" label="الكفيل" value={initial.sponsorId} loading={catalogsLoading} options={sponsors.map(item=>({value:item.id,label:item.registryNameAr}))}/>{renderFields(contract)}</>}<label className="col-span-full grid gap-2 text-sm font-bold">ملاحظات<textarea name="notes" defaultValue={String(initial.notes??"")} className="min-h-24 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 font-normal"/></label></section>
  {!isEmployee&&<section role="tabpanel" hidden={active!=="rider"} className="grid gap-4 sm:grid-cols-2"><h2 className="col-span-full text-lg font-black">بيانات تشغيل المندوب</h2><Select label="مقاس تي شيرت" name="tShirtSize" value={initial.tShirtSize} options={["","ExtraSmall","Small","Medium","Large","ExtraLarge","DoubleExtraLarge","TripleExtraLarge"].map(value=>({value,label:value||"غير محدد"}))} className={selectClass}/><Input name="operationalNotes" label="ملاحظات المندوب" defaultValue={String(initial.operationalNotes??"")}/></section>}
  {error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}</div><footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] bg-slate-50/60 p-4"><p className="text-xs text-[var(--muted)]">راجع الحقول المعلّمة «مطلوب» قبل الحفظ.</p><Button type="submit" loading={saving}><Save size={17}/>{submitLabel}</Button></footer></Card></form>;
}
function CatalogSelect({name,label,value,options,loading}:{name:string;label:string;value:unknown;options:{value:string;label:string}[];loading:boolean}){return <label className="grid gap-2 text-sm font-bold">{label}<select name={name} defaultValue={String(value??"")} disabled={loading} className="h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 font-normal outline-none focus:border-[#1167c9] focus:ring-4 focus:ring-blue-100 disabled:cursor-wait disabled:opacity-60"><option value="">{loading?"جارٍ تحميل الخيارات…":`اختر ${label}`}</option>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
function Select({label,name,value,options,className,required,onChange}:{label:string;name?:string;value:unknown;options:{value:string;label:string}[];className:string;required?:boolean;onChange?:(value:string)=>void}){return <label className="grid gap-2 text-sm font-bold">{label}<select name={name} value={onChange?String(value??""):undefined} defaultValue={onChange?undefined:String(value??"")} required={required} onChange={event=>onChange?.(event.target.value)} className={className}>{options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>}
