export type FieldKind = "text" | "date" | "number" | "boolean" | "csv" | "json" | "select";
export type HrField = { key: string; label: string; labelEn?: string; kind?: FieldKind; required?: boolean; options?: { value: string; label: string; labelEn?: string }[]; source?: "employees" | "document-types" | "leave-types" | "platforms" | "contracts" | "operational-work-types" };
export type HrSection = {
  resource: string;
  title: string;
  titleEn?: string;
  description: string;
  descriptionEn?: string;
  permissionRead: string;
  permissionManage: string;
  fields: HrField[];
  columns: { key: string; label: string; labelEn?: string }[];
  workflow?: "leave" | "absence" | "status";
};

const status = { key: "status", label: "الحالة", labelEn: "Status", kind: "select" as const, required: true, options: [{ value: "Active", label: "نشط", labelEn: "Active" }, { value: "Inactive", label: "غير نشط", labelEn: "Inactive" }, { value: "Draft", label: "مسودة", labelEn: "Draft" }] };
const catalog = (resource: string, title: string, titleEn: string, description: string, descriptionEn: string, read: string, manage: string): HrSection => ({ resource, title, titleEn, description, descriptionEn, permissionRead: read, permissionManage: manage, columns: [{ key: "code", label: "الرمز", labelEn: "Code" }, { key: "nameAr", label: "الاسم العربي", labelEn: "Arabic Name" }, { key: "nameEn", label: "الاسم الإنجليزي", labelEn: "English Name" }, { key: "status", label: "الحالة", labelEn: "Status" }], fields: [{ key: "code", label: "الرمز", labelEn: "Code", required: true }, { key: "nameAr", label: "الاسم العربي", labelEn: "Arabic Name", required: true }, { key: "nameEn", label: "الاسم الإنجليزي", labelEn: "English Name" }, { key: "descriptionAr", label: "الوصف العربي", labelEn: "Arabic Description" }, { key: "descriptionEn", label: "الوصف الإنجليزي", labelEn: "English Description" }, status] });

export const hrSections: Record<string, HrSection> = {
  "job-titles": catalog("job-titles", "المسميات الوظيفية", "Job Titles", "إدارة المسميات وربطها بأنواع العمل التشغيلي.", "Manage job titles and link them to operational work types.", "employees.read", "employees.update"),
  "residency-professions": catalog("residency-professions", "مهن الإقامة", "Residency Professions", "الكتالوج المعتمد لمهن الإقامة.", "Approved catalog for residency professions.", "residency.read", "residency.manage"),
  "operational-work-types": catalog("operational-work-types", "أنواع الأعمال التشغيلية", "Operational Work Types", "أنواع العمل المستخدمة في تكليف الإداريين والمناديب.", "Work types used for assigning staff and riders.", "employees.read", "employees.update"),
  "driver-license-categories": catalog("driver-license-categories", "فئات رخص القيادة", "Driver License Categories", "فئات الرخص المعتمدة في بيانات الالتزام.", "Approved license categories for compliance data.", "licenses.read", "licenses.manage"),
  "document-types": { resource: "document-types", title: "أنواع الوثائق", titleEn: "Document Types", description: "قواعد أنواع الملفات والبيانات المطلوبة لكل وثيقة.", descriptionEn: "Rules and file specifications for each document type.", permissionRead: "documents.read", permissionManage: "documents.catalog.manage", columns: [{key:"code",label:"الرمز",labelEn:"Code"},{key:"nameAr",label:"الاسم",labelEn:"Name"},{key:"requiresFile",label:"ملف مطلوب",labelEn:"File Required"},{key:"status",label:"الحالة",labelEn:"Status"}], fields: [{key:"code",label:"الرمز",labelEn:"Code",required:true},{key:"nameAr",label:"الاسم العربي",labelEn:"Arabic Name",required:true},{key:"nameEn",label:"الاسم الإنجليزي",labelEn:"English Name",required:true},{key:"descriptionAr",label:"الوصف العربي",labelEn:"Arabic Description"},{key:"descriptionEn",label:"الوصف الإنجليزي",labelEn:"English Description"},{key:"appliesToSponsoredInternal",label:"ينطبق على الإداري المكفول",labelEn:"Applies to Sponsored Internal",kind:"boolean"},{key:"appliesToOutsideRider",label:"ينطبق على المندوب الخارجي",labelEn:"Applies to Outside Rider",kind:"boolean"},{key:"appliesToRiderProfile",label:"ينطبق على ملف المندوب",labelEn:"Applies to Rider Profile",kind:"boolean"},{key:"requiresNumber",label:"يتطلب رقمًا",labelEn:"Requires Number",kind:"boolean"},{key:"requiresIssueDate",label:"يتطلب تاريخ إصدار",labelEn:"Requires Issue Date",kind:"boolean"},{key:"requiresExpiryDate",label:"يتطلب تاريخ انتهاء",labelEn:"Requires Expiry Date",kind:"boolean"},{key:"requiresFile",label:"يتطلب ملفًا",labelEn:"Requires File",kind:"boolean"},{key:"allowedMimeTypes",label:"أنواع الملفات المسموحة (مفصولة بفاصلة)",labelEn:"Allowed Mime Types (comma-separated)",kind:"csv"},{key:"maxFileSizeBytes",label:"أقصى حجم بالبايت",labelEn:"Max File Size (Bytes)",kind:"number",required:true},status] },
  "document-requirements": { resource:"document-requirements",title:"متطلبات الوثائق",titleEn:"Document Requirements",description:"تحديد الوثائق الإلزامية وفترات التذكير حسب نوع العلاقة.",descriptionEn:"Define mandatory documents and reminder periods per relationship type.",permissionRead:"documents.read",permissionManage:"documents.catalog.manage",columns:[{key:"documentTypeCode",label:"نوع الوثيقة",labelEn:"Document Type"},{key:"relationshipType",label:"نوع العلاقة",labelEn:"Relationship Type"},{key:"isRequired",label:"إلزامية",labelEn:"Mandatory"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"documentTypeId",label:"نوع الوثيقة",labelEn:"Document Type",kind:"select",source:"document-types",required:true},{key:"relationshipType",label:"نوع العلاقة",labelEn:"Relationship Type",kind:"select",options:[{value:"SponsoredInternal",label:"على الكفالة",labelEn:"Sponsored Internal"},{value:"OutsideRider",label:"مندوب خارجي",labelEn:"Outside Rider"}]},{key:"appliesToRiderProfile",label:"ينطبق على ملف المندوب",labelEn:"Applies to Rider Profile",kind:"boolean"},{key:"isRequired",label:"إلزامية",labelEn:"Mandatory",kind:"boolean"},{key:"reminderOffsetsDays",label:"أيام التذكير (مفصولة بفاصلة)",labelEn:"Reminder Offset Days (comma-separated)",kind:"csv"},{key:"effectiveFrom",label:"ساري من",labelEn:"Effective From",kind:"date",required:true},{key:"effectiveTo",label:"ساري حتى",labelEn:"Effective To",kind:"date"},status] },
  "leave-types": { resource:"leave-types",title:"أنواع الإجازات",titleEn:"Leave Types",description:"إعداد أنواع الإجازات ومتطلبات كل نوع.",descriptionEn:"Setup leave types and requirements for each type.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",columns:[{key:"code",label:"الرمز",labelEn:"Code"},{key:"nameAr",label:"الاسم",labelEn:"Name"},{key:"maximumCalendarDays",label:"الحد الأقصى",labelEn:"Max Days"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"code",label:"الرمز",labelEn:"Code",required:true},{key:"nameAr",label:"الاسم العربي",labelEn:"Arabic Name",required:true},{key:"nameEn",label:"الاسم الإنجليزي",labelEn:"English Name",required:true},{key:"descriptionAr",label:"الوصف العربي",labelEn:"Arabic Description"},{key:"descriptionEn",label:"الوصف الإنجليزي",labelEn:"English Description"},{key:"requiresBalance",label:"يتطلب رصيدًا",labelEn:"Requires Balance",kind:"boolean"},{key:"requiresHrDocuments",label:"يتطلب وثائق موارد بشرية",labelEn:"Requires HR Documents",kind:"boolean"},{key:"requiresExitReentryVisa",label:"يتطلب تأشيرة خروج وعودة",labelEn:"Requires Exit/Reentry Visa",kind:"boolean"},{key:"maximumCalendarDays",label:"أقصى عدد أيام",labelEn:"Max Days",kind:"number"},status] },
  "leave-approval-workflows": { resource:"leave-approval-workflows",title:"مسارات اعتماد الإجازات",titleEn:"Leave Approval Workflows",description:"بناء مسارات الاعتماد وخطواتها وأولوياتها.",descriptionEn:"Build approval workflows, steps, and priorities.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",columns:[{key:"code",label:"الرمز",labelEn:"Code"},{key:"nameAr",label:"المسار",labelEn:"Workflow"},{key:"version",label:"الإصدار",labelEn:"Version"},{key:"priority",label:"الأولوية",labelEn:"Priority"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"code",label:"الرمز",labelEn:"Code",required:true},{key:"nameAr",label:"الاسم العربي",labelEn:"Arabic Name",required:true},{key:"nameEn",label:"الاسم الإنجليزي",labelEn:"English Name",required:true},{key:"version",label:"الإصدار",labelEn:"Version",kind:"number",required:true},{key:"leaveTypeId",label:"نوع الإجازة",labelEn:"Leave Type"},{key:"relationshipType",label:"نوع العلاقة",labelEn:"Relationship Type"},{key:"appliesToRider",label:"خاص بالمناديب",labelEn:"Applies to Riders",kind:"boolean"},{key:"clientPlatformId",label:"المنصة",labelEn:"Platform"},{key:"priority",label:"الأولوية",labelEn:"Priority",kind:"number",required:true},{key:"effectiveFrom",label:"ساري من",labelEn:"Effective From",kind:"date",required:true},{key:"effectiveTo",label:"ساري حتى",labelEn:"Effective To",kind:"date"},status,{key:"steps",label:"خطوات الاعتماد (JSON)",labelEn:"Approval Steps (JSON)",kind:"json",required:true}] },
  "leave-requests": { resource:"leave-requests",title:"طلبات الإجازات",titleEn:"Leave Requests",description:"إنشاء الطلبات ومتابعة الاعتماد والتغييرات والإلغاء.",descriptionEn:"Create requests and track approvals, changes, and cancellations.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",workflow:"leave",columns:[{key:"requestNumber",label:"رقم الطلب",labelEn:"Request #"},{key:"employeeNameAr",label:"الموظف",labelEn:"Employee"},{key:"leaveTypeNameAr",label:"نوع الإجازة",labelEn:"Leave Type"},{key:"startDate",label:"من",labelEn:"From"},{key:"endDate",label:"إلى",labelEn:"To"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"employeeId",label:"الموظف",labelEn:"Employee",kind:"select",source:"employees",required:true},{key:"leaveTypeId",label:"نوع الإجازة",labelEn:"Leave Type",kind:"select",source:"leave-types",required:true},{key:"startDate",label:"تاريخ البداية",labelEn:"Start Date",kind:"date",required:true},{key:"endDate",label:"تاريخ النهاية",labelEn:"End Date",kind:"date",required:true},{key:"expectedReturnDate",label:"تاريخ العودة المتوقع",labelEn:"Expected Return Date",kind:"date",required:true},{key:"reason",label:"السبب",labelEn:"Reason",required:true},{key:"destinationCountryCode",label:"رمز دولة الوجهة",labelEn:"Destination Country Code"},{key:"contactPhoneDuringLeave",label:"هاتف التواصل أثناء الإجازة",labelEn:"Contact Phone During Leave"},{key:"emergencyContactName",label:"اسم اتصال الطوارئ",labelEn:"Emergency Contact Name"},{key:"emergencyContactPhone",label:"هاتف الطوارئ",labelEn:"Emergency Contact Phone"},{key:"relatedClientContractId",label:"عقد العميل",labelEn:"Client Contract",kind:"select",source:"contracts"},{key:"notes",label:"ملاحظات",labelEn:"Notes"}] },
  "absence-cases": { resource:"absence-cases",title:"حالات الغياب",titleEn:"Absence Cases",description:"متابعة بلاغات الغياب ومسار المعالجة والمهلة النظامية.",descriptionEn:"Track absence reports, processing path, and statutory deadline.",permissionRead:"absence_cases.read",permissionManage:"absence_cases.manage",workflow:"absence",columns:[{key:"caseNumber",label:"رقم الحالة",labelEn:"Case #"},{key:"employeeNameAr",label:"الموظف",labelEn:"Employee"},{key:"absenceDate",label:"تاريخ الغياب",labelEn:"Absence Date"},{key:"currentPath",label:"المسار",labelEn:"Path"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"employeeId",label:"الموظف",labelEn:"Employee",required:true},{key:"absenceDate",label:"تاريخ الغياب",labelEn:"Absence Date",kind:"date",required:true},{key:"currentPath",label:"المسار",labelEn:"Path",kind:"select",required:true,options:[{value:"ReportedToAuthorities",label:"بلاغ للجهات",labelEn:"Reported to Authorities"},{value:"ExitOrSystemOutage",label:"خروج أو انقطاع نظامي",labelEn:"Exit / System Outage"}]},{key:"reportedToAuthoritiesDate",label:"تاريخ البلاغ",labelEn:"Report Date",kind:"date"},{key:"authorityReportReference",label:"مرجع البلاغ",labelEn:"Report Reference"},{key:"exitOrOutageDate",label:"تاريخ الخروج أو الانقطاع",labelEn:"Exit/Outage Date",kind:"date"},{key:"exitVisaNumber",label:"رقم تأشيرة الخروج",labelEn:"Exit Visa #"},{key:"removalDeadline",label:"المهلة النهائية",labelEn:"Deadline",kind:"date",required:true},{key:"notes",label:"ملاحظات",labelEn:"Notes"}] },
  "employee-status-change-requests": { resource:"employee-status-change-requests",title:"طلبات تغيير حالة الموظف",titleEn:"Employee Status Change Requests",description:"طلب تغيير الحالة ومراجعة القرار النهائي.",descriptionEn:"Request status changes and review final decisions.",permissionRead:"employee_status_changes.read",permissionManage:"employee_status_changes.manage",workflow:"status",columns:[{key:"requestNumber",label:"رقم الطلب",labelEn:"Request #"},{key:"employeeNameAr",label:"الموظف",labelEn:"Employee"},{key:"fromStatus",label:"من",labelEn:"From"},{key:"requestedStatus",label:"إلى",labelEn:"To"},{key:"effectiveFrom",label:"تاريخ السريان",labelEn:"Effective From"},{key:"status",label:"الحالة",labelEn:"Status"}],fields:[{key:"employeeId",label:"الموظف",labelEn:"Employee",required:true},{key:"requestedStatus",label:"الحالة المطلوبة",labelEn:"Requested Status",kind:"select",required:true,options:["Draft","Onboarding","Active","Suspended","OnLeave","Terminated","Archived"].map(value=>({value,label:value,labelEn:value}))},{key:"effectiveFrom",label:"تاريخ السريان",labelEn:"Effective From",kind:"date",required:true},{key:"reason",label:"السبب",labelEn:"Reason",required:true}] },
};
