export type FieldKind = "text" | "date" | "number" | "boolean" | "csv" | "json" | "select";
export type HrField = { key: string; label: string; kind?: FieldKind; required?: boolean; options?: { value: string; label: string }[]; source?: "employees" | "document-types" | "leave-types" | "platforms" | "contracts" | "operational-work-types" };
export type HrSection = {
  resource: string;
  title: string;
  description: string;
  permissionRead: string;
  permissionManage: string;
  fields: HrField[];
  columns: { key: string; label: string }[];
  workflow?: "leave" | "absence" | "status";
};

const status = { key: "status", label: "الحالة", kind: "select" as const, required: true, options: [{ value: "Active", label: "نشط" }, { value: "Inactive", label: "غير نشط" }, { value: "Draft", label: "مسودة" }] };
const catalog = (resource: string, title: string, description: string, read: string, manage: string): HrSection => ({ resource, title, description, permissionRead: read, permissionManage: manage, columns: [{ key: "code", label: "الرمز" }, { key: "nameAr", label: "الاسم العربي" }, { key: "nameEn", label: "الاسم الإنجليزي" }, { key: "status", label: "الحالة" }], fields: [{ key: "code", label: "الرمز", required: true }, { key: "nameAr", label: "الاسم العربي", required: true }, { key: "nameEn", label: "الاسم الإنجليزي" }, { key: "descriptionAr", label: "الوصف العربي" }, { key: "descriptionEn", label: "الوصف الإنجليزي" }, status] });

export const hrSections: Record<string, HrSection> = {
  "job-titles": catalog("job-titles", "المسميات الوظيفية", "إدارة المسميات وربطها بأنواع العمل التشغيلي.", "employees.read", "employees.update"),
  "residency-professions": catalog("residency-professions", "مهن الإقامة", "الكتالوج المعتمد لمهن الإقامة.", "residency.read", "residency.manage"),
  "operational-work-types": catalog("operational-work-types", "أنواع الأعمال التشغيلية", "أنواع العمل المستخدمة في تكليف الإداريين والمناديب.", "employees.read", "employees.update"),
  "driver-license-categories": catalog("driver-license-categories", "فئات رخص القيادة", "فئات الرخص المعتمدة في بيانات الالتزام.", "licenses.read", "licenses.manage"),
  "document-types": { resource: "document-types", title: "أنواع الوثائق", description: "قواعد أنواع الملفات والبيانات المطلوبة لكل وثيقة.", permissionRead: "documents.read", permissionManage: "documents.catalog.manage", columns: [{key:"code",label:"الرمز"},{key:"nameAr",label:"الاسم"},{key:"requiresFile",label:"ملف مطلوب"},{key:"status",label:"الحالة"}], fields: [{key:"code",label:"الرمز",required:true},{key:"nameAr",label:"الاسم العربي",required:true},{key:"nameEn",label:"الاسم الإنجليزي",required:true},{key:"descriptionAr",label:"الوصف العربي"},{key:"descriptionEn",label:"الوصف الإنجليزي"},{key:"appliesToSponsoredInternal",label:"ينطبق على الإداري المكفول",kind:"boolean"},{key:"appliesToOutsideRider",label:"ينطبق على المندوب الخارجي",kind:"boolean"},{key:"appliesToRiderProfile",label:"ينطبق على ملف المندوب",kind:"boolean"},{key:"requiresNumber",label:"يتطلب رقمًا",kind:"boolean"},{key:"requiresIssueDate",label:"يتطلب تاريخ إصدار",kind:"boolean"},{key:"requiresExpiryDate",label:"يتطلب تاريخ انتهاء",kind:"boolean"},{key:"requiresFile",label:"يتطلب ملفًا",kind:"boolean"},{key:"allowedMimeTypes",label:"أنواع الملفات المسموحة (مفصولة بفاصلة)",kind:"csv"},{key:"maxFileSizeBytes",label:"أقصى حجم بالبايت",kind:"number",required:true},status] },
  "document-requirements": { resource:"document-requirements",title:"متطلبات الوثائق",description:"تحديد الوثائق الإلزامية وفترات التذكير حسب نوع العلاقة.",permissionRead:"documents.read",permissionManage:"documents.catalog.manage",columns:[{key:"documentTypeCode",label:"نوع الوثيقة"},{key:"relationshipType",label:"نوع العلاقة"},{key:"isRequired",label:"إلزامية"},{key:"status",label:"الحالة"}],fields:[{key:"documentTypeId",label:"نوع الوثيقة",kind:"select",source:"document-types",required:true},{key:"relationshipType",label:"نوع العلاقة",kind:"select",options:[{value:"SponsoredInternal",label:"إداري مكفول"},{value:"OutsideRider",label:"مندوب خارجي"}]},{key:"appliesToRiderProfile",label:"ينطبق على ملف المندوب",kind:"boolean"},{key:"isRequired",label:"إلزامية",kind:"boolean"},{key:"reminderOffsetsDays",label:"أيام التذكير (مفصولة بفاصلة)",kind:"csv"},{key:"effectiveFrom",label:"ساري من",kind:"date",required:true},{key:"effectiveTo",label:"ساري حتى",kind:"date"},status] },
  "leave-types": { resource:"leave-types",title:"أنواع الإجازات",description:"إعداد أنواع الإجازات ومتطلبات كل نوع.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",columns:[{key:"code",label:"الرمز"},{key:"nameAr",label:"الاسم"},{key:"maximumCalendarDays",label:"الحد الأقصى"},{key:"status",label:"الحالة"}],fields:[{key:"code",label:"الرمز",required:true},{key:"nameAr",label:"الاسم العربي",required:true},{key:"nameEn",label:"الاسم الإنجليزي",required:true},{key:"descriptionAr",label:"الوصف العربي"},{key:"descriptionEn",label:"الوصف الإنجليزي"},{key:"requiresBalance",label:"يتطلب رصيدًا",kind:"boolean"},{key:"requiresHrDocuments",label:"يتطلب وثائق موارد بشرية",kind:"boolean"},{key:"requiresExitReentryVisa",label:"يتطلب تأشيرة خروج وعودة",kind:"boolean"},{key:"maximumCalendarDays",label:"أقصى عدد أيام",kind:"number"},status] },
  "leave-approval-workflows": { resource:"leave-approval-workflows",title:"مسارات اعتماد الإجازات",description:"بناء مسارات الاعتماد وخطواتها وأولوياتها.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",columns:[{key:"code",label:"الرمز"},{key:"nameAr",label:"المسار"},{key:"version",label:"الإصدار"},{key:"priority",label:"الأولوية"},{key:"status",label:"الحالة"}],fields:[{key:"code",label:"الرمز",required:true},{key:"nameAr",label:"الاسم العربي",required:true},{key:"nameEn",label:"الاسم الإنجليزي",required:true},{key:"version",label:"الإصدار",kind:"number",required:true},{key:"leaveTypeId",label:"معرّف نوع الإجازة"},{key:"relationshipType",label:"نوع العلاقة"},{key:"appliesToRider",label:"خاص بالمناديب",kind:"boolean"},{key:"clientPlatformId",label:"معرّف المنصة"},{key:"priority",label:"الأولوية",kind:"number",required:true},{key:"effectiveFrom",label:"ساري من",kind:"date",required:true},{key:"effectiveTo",label:"ساري حتى",kind:"date"},status,{key:"steps",label:"خطوات الاعتماد (JSON)",kind:"json",required:true}] },
  "leave-requests": { resource:"leave-requests",title:"طلبات الإجازات",description:"إنشاء الطلبات ومتابعة الاعتماد والتغييرات والإلغاء.",permissionRead:"leave_requests.read",permissionManage:"leave_requests.manage",workflow:"leave",columns:[{key:"requestNumber",label:"رقم الطلب"},{key:"employeeNameAr",label:"الموظف"},{key:"leaveTypeNameAr",label:"نوع الإجازة"},{key:"startDate",label:"من"},{key:"endDate",label:"إلى"},{key:"status",label:"الحالة"}],fields:[{key:"employeeId",label:"الموظف",kind:"select",source:"employees",required:true},{key:"leaveTypeId",label:"نوع الإجازة",kind:"select",source:"leave-types",required:true},{key:"startDate",label:"تاريخ البداية",kind:"date",required:true},{key:"endDate",label:"تاريخ النهاية",kind:"date",required:true},{key:"expectedReturnDate",label:"تاريخ العودة المتوقع",kind:"date",required:true},{key:"reason",label:"السبب",required:true},{key:"destinationCountryCode",label:"رمز دولة الوجهة"},{key:"contactPhoneDuringLeave",label:"هاتف التواصل أثناء الإجازة"},{key:"emergencyContactName",label:"اسم اتصال الطوارئ"},{key:"emergencyContactPhone",label:"هاتف الطوارئ"},{key:"relatedClientContractId",label:"عقد العميل",kind:"select",source:"contracts"},{key:"notes",label:"ملاحظات"}] },
  "absence-cases": { resource:"absence-cases",title:"حالات الغياب",description:"متابعة بلاغات الغياب ومسار المعالجة والمهلة النظامية.",permissionRead:"absence_cases.read",permissionManage:"absence_cases.manage",workflow:"absence",columns:[{key:"caseNumber",label:"رقم الحالة"},{key:"employeeNameAr",label:"الموظف"},{key:"absenceDate",label:"تاريخ الغياب"},{key:"currentPath",label:"المسار"},{key:"status",label:"الحالة"}],fields:[{key:"employeeId",label:"معرّف الموظف",required:true},{key:"absenceDate",label:"تاريخ الغياب",kind:"date",required:true},{key:"currentPath",label:"المسار",kind:"select",required:true,options:[{value:"ReportedToAuthorities",label:"بلاغ للجهات"},{value:"ExitOrSystemOutage",label:"خروج أو انقطاع نظامي"}]},{key:"reportedToAuthoritiesDate",label:"تاريخ البلاغ",kind:"date"},{key:"authorityReportReference",label:"مرجع البلاغ"},{key:"exitOrOutageDate",label:"تاريخ الخروج أو الانقطاع",kind:"date"},{key:"exitVisaNumber",label:"رقم تأشيرة الخروج"},{key:"removalDeadline",label:"المهلة النهائية",kind:"date",required:true},{key:"notes",label:"ملاحظات"}] },
  "employee-status-change-requests": { resource:"employee-status-change-requests",title:"طلبات تغيير حالة الموظف",description:"طلب تغيير الحالة ومراجعة القرار النهائي.",permissionRead:"employee_status_changes.read",permissionManage:"employee_status_changes.manage",workflow:"status",columns:[{key:"requestNumber",label:"رقم الطلب"},{key:"employeeNameAr",label:"الموظف"},{key:"fromStatus",label:"من"},{key:"requestedStatus",label:"إلى"},{key:"effectiveFrom",label:"تاريخ السريان"},{key:"status",label:"الحالة"}],fields:[{key:"employeeId",label:"معرّف الموظف",required:true},{key:"requestedStatus",label:"الحالة المطلوبة",kind:"select",required:true,options:["Draft","Onboarding","Active","Suspended","OnLeave","Terminated","Archived"].map(value=>({value,label:value}))},{key:"effectiveFrom",label:"تاريخ السريان",kind:"date",required:true},{key:"reason",label:"السبب",required:true}] },
};
