import { authFetch } from "../auth/api";
export type Housing = {id:string;code:string;nameAr:string;nameEn:string;cityId:string;cityAr:string;totalCapacity:number;currentResidents:number;availableCapacity:number;contactPhone:string|null;openedDate:string|null;closedDate:string|null;status:string;statusReason:string|null;notes:string|null;rowVersion:string;address?:Record<string,string|null>};
export type HousingPeriod={id:string;housingId:string;employeeId:string;iqamaNo:string|null;employeeNameAr:string;effectiveFrom:string;effectiveTo:string|null;startReason:string|null;endReason:string|null;capacityOverrideUsed:boolean;capacityOverrideReason:string|null};
export const listHousing=()=>authFetch<Housing[]>("/api/housing");
export const getHousing=(id:string)=>authFetch<Housing>(`/api/housing/${encodeURIComponent(id)}`);
export const createHousing=(payload:Record<string,unknown>)=>authFetch<Housing>("/api/housing",{method:"POST",body:JSON.stringify(payload)});
export const updateHousing=(id:string,payload:Record<string,unknown>)=>authFetch<Housing>(`/api/housing/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify(payload)});
export const archiveHousing=(id:string,reason:string,rowVersion:string)=>authFetch<void>(`/api/housing/${encodeURIComponent(id)}/archive`,{method:"PATCH",body:JSON.stringify({reason,rowVersion})});
export const listResidents=(id:string,currentOnly=false)=>authFetch<HousingPeriod[]>(`/api/housing/${encodeURIComponent(id)}/residents?currentOnly=${currentOnly}`);
export const assignResident=(id:string,payload:Record<string,unknown>)=>authFetch<HousingPeriod[]>(`/api/housing/${encodeURIComponent(id)}/residents`,{method:"POST",body:JSON.stringify(payload)});
export const closeResidence=(periodId:string,effectiveTo:string,reason:string)=>authFetch<void>(`/api/housing/residence-periods/${encodeURIComponent(periodId)}/close`,{method:"POST",body:JSON.stringify({effectiveTo,reason})});
export const listSupervisors=(id:string,currentOnly=false)=>authFetch<HousingPeriod[]>(`/api/housing/${encodeURIComponent(id)}/supervisors?currentOnly=${currentOnly}`);
export const assignSupervisor=(id:string,payload:Record<string,unknown>)=>authFetch<HousingPeriod[]>(`/api/housing/${encodeURIComponent(id)}/supervisors`,{method:"POST",body:JSON.stringify(payload)});
export const closeSupervisor=(periodId:string,effectiveTo:string,reason:string)=>authFetch<void>(`/api/housing/supervisor-periods/${encodeURIComponent(periodId)}/close`,{method:"POST",body:JSON.stringify({effectiveTo,reason})});
