import {
  CircleUserRound,
  BriefcaseBusiness,
  ClipboardList,
  Building2,
  LayoutDashboard,
  House,
  ShieldCheck,
  ShieldAlert,
  Users,
  Layers,
  Server,
  History,
  FileText,
  Car,
  Key,
  Wrench,
  AlertTriangle,
  BookOpen,
  Repeat,
  Smartphone,
  UserCheck,
  ArrowLeftRight,
  Archive,
  Gauge,
  Fuel,
  Package,
  BadgeDollarSign,
  BarChart3,
  CalendarCheck,
  FileSpreadsheet,
  Droplets,
  GitBranch,
  Clock,
  CreditCard,
  Truck,
  PackageCheck,
  ShoppingBag,
  type LucideIcon,
} from "lucide-react";

export type Role = "admin" | "manager" | "member" | "accountant";

export type NavItem = {
  label: string;
  labelKey?: string;
  href?: string;
  icon: LucideIcon;
  roles?: Role[];
  permission?: string;
  permissionsAny?: string[];
  children?: NavItem[];
};

export const navigation: NavItem[] = [
  {
    label: "الرئيسية",
    labelKey: "nav.dashboard",
    href: "/admin",
    icon: LayoutDashboard,
    roles: ["admin", "manager", "member", "accountant"],
  },
  {
    label: "الموارد البشرية",
    labelKey: "nav.hr",
    icon: BriefcaseBusiness,
    roles: ["admin", "manager", "member", "accountant"],
    children: [
      {
        label: "لوحة مؤشرات الموارد البشرية",
        labelKey: "nav.hrDashboard",
        href: "/admin/hr/dashboard",
        icon: LayoutDashboard,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "reports.read",
      },
      {
        label: "لوحة مؤشرات الالتزام",
        labelKey: "nav.peopleComplianceDashboard",
        href: "/admin/people-compliance",
        icon: ShieldCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "reports.read",
      },
      {
        label: "جميع الإداريين والمناديب",
        labelKey: "nav.employees",
        href: "/admin/employees",
        icon: Users,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "employees.read",
      },
      {
        label: "كتالوجات الموظفين",
        labelKey: "nav.catalogs",
        href: "/admin/hr/catalogs",
        icon: BriefcaseBusiness,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "employees.read",
          "residency.read",
          "licenses.read",
          "sponsors.read",
          "operating_cities.read",
        ],
      },
      {
        label: "وثائق الموظفين والمناديب",
        labelKey: "nav.documents",
        href: "/admin/hr/documents",
        icon: FileText,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "documents.read",
      },
      {
        label: "التأمين الطبي",
        labelKey: "nav.insurance",
        href: "/admin/hr/insurance",
        icon: ShieldCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "insurance.read",
      },
      {
        label: "التأمينات الاجتماعية",
        labelKey: "nav.socialInsurance",
        href: "/admin/hr/payroll-employees",
        icon: Building2,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "employees.read",
      },
      {
        label: "حالات الغياب",
        labelKey: "nav.absenceCases",
        href: "/admin/hr/absence-cases",
        icon: ClipboardList,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "absence_cases.read",
      },
      {
        label: "طلبات الإجازات",
        labelKey: "nav.leaveRequests",
        href: "/admin/hr/leave-requests",
        icon: CalendarCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "leave_requests.read",
      },
      {
        label: "طلبات تغيير الحالة",
        labelKey: "nav.statusChangeRequests",
        href: "/admin/hr/employee-status-change-requests",
        icon: ClipboardList,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "employee_status_changes.read",
      },
      {
        label: "نماذج الموارد البشرية",
        labelKey: "nav.hrForms",
        href: "/admin/hr/forms",
        icon: FileText,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "employees.read",
      },
      {
        label: "تنبيهات الوثائق",
        labelKey: "nav.expiryCompliance",
        href: "/admin/hr/compliance-expiries",
        icon: ShieldAlert,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "employees.read",
      },
      {
        label: "المناديب الخارجيين",
        labelKey: "nav.externalRiders",
        href: "/admin/hr/external-riders",
        icon: Users,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "riders.read",
      },
    ],
  },
  {
    label: "إدارة السكن",
    labelKey: "nav.housing",
    href: "/admin/housing",
    icon: House,
    roles: ["admin", "manager", "member", "accountant"],
    permission: "housing.read",
  },
  {
    label: "إدارة المنصات",
    labelKey: "nav.platforms",
    icon: Layers,
    roles: ["admin", "manager", "member", "accountant"],
    permissionsAny: ["platform_accounts.read", "platform_assignments.read"],
    children: [
      {
        label: "لوحة مؤشرات العمليات",
        labelKey: "nav.operationsDashboard",
        href: "/admin/operations/dashboard",
        icon: LayoutDashboard,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "reports.read",
      },
      {
        label: "المنصات",
        labelKey: "nav.platformList",
        href: "/admin/platforms",
        icon: Layers,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "platform_accounts.read",
      },
      {
        label: "حسابات المنصات",
        labelKey: "nav.platformAccounts",
        href: "/admin/platforms/accounts",
        icon: Server,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "platform_accounts.read",
      },
      {
        label: "سجل العمل للمندوب",
        labelKey: "nav.riderPlatformHistory",
        href: "/admin/platforms/rider-history",
        icon: History,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "platform_assignments.read",
      },
    ],
  },
  {
    label: "إدارة الأسطول والمركبات",
    labelKey: "nav.fleet",
    icon: Car,
    roles: ["admin", "manager", "member", "accountant"],
    permissionsAny: [
      "fleet.vehicles.read",
      "fleet.assignments.read",
      "fleet.issues.read",
      "fleet.accidents.read",
      "fleet.compliance.read",
      "fleet.daily_distances.read",
      "fuel.read",
      "fuel.manage",
      "fuel.import",
    ],
    children: [
      {
        label: "لوحة مؤشرات الأسطول",
        labelKey: "nav.fleetDashboard",
        href: "/admin/fleet/dashboard",
        icon: LayoutDashboard,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "reports.read",
      },
      {
        label: "المركبات",
        labelKey: "nav.vehicles",
        href: "/admin/fleet/vehicles",
        icon: Car,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.vehicles.read",
      },
      {
        label: "بطاقات الوقود",
        labelKey: "nav.fuelCards",
        href: "/admin/fleet/fuel-cards",
        icon: Fuel,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fuel.read", "fuel.manage", "fuel.import"],
      },
      {
        label: "التعيينات والاستلام",
        labelKey: "nav.vehicleAssignments",
        href: "/admin/fleet/assignments",
        icon: Key,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.assignments.read",
      },
      {
        label: "المسافات اليومية (GPS والعداد)",
        labelKey: "nav.vehicleDailyDistances",
        href: "/admin/fleet/daily-distances",
        icon: Gauge,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fleet.daily_distances.read", "fleet.vehicles.read", "fleet.assignments.read"],
      },
      {
        label: "الأعطال والمشاكل",
        labelKey: "nav.vehicleIssues",
        href: "/admin/fleet/issues",
        icon: Wrench,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.issues.read",
      },
      {
        label: "متابعة تجديد التراخيص",
        labelKey: "nav.vehicleCompliance",
        href: "/admin/fleet/compliance",
        icon: ShieldCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.compliance.read",
      },
      {
        label: "الكتالوجات والموردون",
        labelKey: "nav.vehicleCatalogs",
        href: "/admin/fleet/catalogs",
        icon: BookOpen,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.vehicles.read",
      },
    ],
  },
  {
    label: "إدارة الحوادث والمطالبات",
    labelKey: "nav.accidentsManagement",
    icon: AlertTriangle,
    roles: ["admin", "manager", "member", "accountant"],
    permission: "fleet.accidents.read",
    children: [
      {
        label: "سجل الحوادث الأصلية",
        labelKey: "nav.accidentsRegistry",
        href: "/admin/fleet/accidents",
        icon: FileText,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.accidents.read",
      },
      {
        label: "متابعة دورة المطالبات",
        labelKey: "nav.claimWorkflows",
        href: "/admin/fleet/accidents/workflows",
        icon: GitBranch,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.accidents.read",
      },
      {
        label: "المهل والمتأخرات الحرجة",
        labelKey: "nav.overdueClaims",
        href: "/admin/fleet/accidents/overdue",
        icon: Clock,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.accidents.read",
      },
      {
        label: "استرداد الأقساط",
        labelKey: "nav.installmentRefunds",
        href: "/admin/fleet/accidents/installments",
        icon: CreditCard,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.accidents.read",
      },
      {
        label: "السطحات ونقل المركبات",
        labelKey: "nav.towingReceipts",
        href: "/admin/fleet/accidents/towing",
        icon: Truck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "fleet.accidents.read",
      },
    ],
  },
  {
    label: "ربط المركبات بالمنصات",
    labelKey: "nav.vehicleAccountAssignments",
    icon: Server,
    roles: ["admin", "manager", "member", "accountant"],
    permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
    children: [
      {
        label: "جميع الربطات النشطة",
        labelKey: "nav.vehicleAccountAssignmentsAll",
        href: "/admin/fleet/vehicle-account-assignments",
        icon: Server,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "طلبات التبديل المعلقة",
        labelKey: "nav.vehicleAccountAssignmentsSwitches",
        href: "/admin/fleet/vehicle-account-assignments/switches",
        icon: Repeat,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "التحذيرات التشغيلية",
        labelKey: "nav.vehicleAccountAssignmentsProblems",
        href: "/admin/fleet/vehicle-account-assignments/problems",
        icon: AlertTriangle,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "عقود تأجير الكفلاء (كيتا)",
        labelKey: "nav.sponsorVehicleLeases",
        href: "/admin/fleet/vehicle-account-assignments/leases",
        icon: FileText,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
    ],
  },
  {
    label: "إدارة شرائح الاتصال (SIM)",
    labelKey: "nav.phoneSimsGroup",
    icon: Smartphone,
    roles: ["admin", "manager", "member", "accountant"],
    permission: "phone_sims.read",
    children: [
      {
        label: "جميع الشرائح والمخزون",
        labelKey: "nav.phoneSimsAll",
        href: "/admin/fleet/phone-sims",
        icon: Smartphone,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "phone_sims.read",
      },
      {
        label: "تعيينات المناديب والعهد",
        labelKey: "nav.phoneSimsAssignments",
        href: "/admin/fleet/phone-sims/assignments",
        icon: UserCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "phone_sims.read",
      },
      {
        label: "سجل نقل المسؤوليات",
        labelKey: "nav.phoneSimsTransfers",
        href: "/admin/fleet/phone-sims/transfers",
        icon: ArrowLeftRight,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "phone_sims.read",
      },
      {
        label: "الشرائح المعلقة والمؤرشفة",
        labelKey: "nav.phoneSimsArchived",
        href: "/admin/fleet/phone-sims/archived",
        icon: Archive,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "phone_sims.read",
      },
    ],
  },
  {
    label: "الصيانة والمخزون والورش",
    labelKey: "nav.maintenanceGroup",
    icon: Wrench,
    roles: ["admin", "manager", "member", "accountant"],
    permissionsAny: [
      "maintenance.locations.read",
      "maintenance.work_orders.read",
      "maintenance.oil.read",
      "maintenance.external_jobs.read",
      "maintenance.profit_reports.read",
      "inventory.items.read",
      "inventory.stock.read",
      "inventory.cost_layers.read",
      "inventory.receipts.manage",
      "inventory.supply_requests.read",
      "inventory.supply_requests.approve",
      "inventory.supply_requests.submit",
    ],
    children: [
      {
        label: "لوحة مؤشرات الصيانة والمخزون",
        labelKey: "nav.maintenanceInventoryDashboard",
        href: "/admin/maintenance/dashboard",
        icon: LayoutDashboard,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "reports.read",
      },
      {
        label: "أوامر الصيانة والعمل",
        labelKey: "nav.maintenanceWorkOrders",
        href: "/admin/maintenance/work-orders/orders",
        icon: Wrench,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.work_orders.read",
      },
      {
        label: "تذكيرات واستحقاقات الزيوت",
        labelKey: "nav.maintenanceOilReminders",
        href: "/admin/maintenance/work-orders/reminders",
        icon: Droplets,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.oil.read",
      },
      {
        label: "ورشة الرياض والعمليات الخارجية",
        labelKey: "nav.maintenanceRiyadhWorkshop",
        href: "/admin/maintenance/workshops/orders",
        icon: BadgeDollarSign,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.external_jobs.read",
      },
      {
        label: "تقرير أرباح ورشة الرياض",
        labelKey: "nav.maintenanceRiyadhProfit",
        href: "/admin/maintenance/workshops/profit",
        icon: BarChart3,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.profit_reports.read",
      },
      {
        label: "فواتير واستلام المشتريات",
        labelKey: "nav.maintenanceReceipts",
        href: "/admin/maintenance/inventory/receipts",
        icon: FileSpreadsheet,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "inventory.receipts.manage",
          "inventory.stock.read",
        ],
      },
      {
        label: "أرصدة المخزون",
        labelKey: "nav.maintenanceBalances",
        href: "/admin/maintenance/inventory/balances",
        icon: Layers,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "inventory.stock.read",
      },
      {
        label: "براميل الزيوت وإدارة الفاقد",
        labelKey: "nav.maintenanceBarrels",
        href: "/admin/maintenance/inventory/barrels",
        icon: Droplets,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "maintenance.oil.read",
          "inventory.stock.read",
        ],
      },
      {
        label: "التحويلات والمرتجعات والعهد",
        labelKey: "nav.maintenanceTransfers",
        href: "/admin/maintenance/inventory/transfers",
        icon: ArrowLeftRight,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "inventory.receipts.manage",
          "inventory.stock.read",
        ],
      },
      {
        label: "طلبات صرف المستودع",
        labelKey: "nav.maintenanceSupplyRequests",
        href: "/admin/maintenance/inventory/supply-requests",
        icon: PackageCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "inventory.supply_requests.read",
          "inventory.supply_requests.approve",
          "inventory.stock.move",
        ],
      },
      {
        label: "طلب مستلزمات مناديب",
        labelKey: "nav.maintenanceRequestRiderItems",
        href: "/admin/maintenance/inventory/request-rider-items",
        icon: ShoppingBag,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "inventory.supply_requests.submit",
      },
      {
        label: "كتالوج قطع الغيار والأصناف",
        labelKey: "nav.maintenanceItemsCatalog",
        href: "/admin/maintenance/setup/items",
        icon: Package,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "inventory.items.read",
      },
      {
        label: "مواقع وورش الصيانة والمستودعات",
        labelKey: "nav.maintenanceLocations",
        href: "/admin/maintenance/setup/locations",
        icon: Building2,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.locations.read",
      },
      {
        label: "موردو قطع الغيار والخدمات",
        labelKey: "nav.maintenanceSuppliers",
        href: "/admin/maintenance/setup/suppliers",
        icon: Users,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "maintenance.locations.read",
      },
      {
        label: "خطط وبرامج الصيانة الدورية",
        labelKey: "nav.maintenancePlans",
        href: "/admin/maintenance/setup/plans",
        icon: CalendarCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: [
          "maintenance.locations.read",
          "inventory.items.read",
        ],
      },
    ],
  },
  {
    label: "إدارة المستخدمين",
    labelKey: "nav.userManagement",
    icon: ShieldCheck,
    roles: ["admin", "manager", "member", "accountant"],
    children: [
      {
        label: "المستخدمون",
        labelKey: "nav.users",
        href: "/admin/users",
        icon: Users,
        roles: ["admin", "manager", "member", "accountant"],
        permission: "users.read",
      },
      {
        label: "الأدوار والصلاحيات",
        labelKey: "nav.rolesAndPermissions",
        href: "/admin/users/roles",
        icon: ShieldCheck,
        roles: ["admin", "manager", "member", "accountant"],
        permissionsAny: ["roles.read", "permissions.read"],
      },
    ],
  },
  {
    label: "ملفي الشخصي",
    labelKey: "nav.profile",
    href: "/admin/profile",
    icon: CircleUserRound,
    roles: ["admin", "manager", "member", "accountant"],
  },
];
