import {
  CircleUserRound,
  BriefcaseBusiness,
  ClipboardList,
  Building2,
  LayoutDashboard,
  House,
  ShieldCheck,
  ShieldAlert,
  Users,
  Layers,
  Server,
  History,
  FileText,
  Car,
  Key,
  Wrench,
  AlertTriangle,
  BookOpen,
  Repeat,
  Smartphone,
  UserCheck,
  ArrowLeftRight,
  Archive,
  Gauge,
  Fuel,
  type LucideIcon,
} from "lucide-react";
export type Role = "admin" | "member" | "accountant";
export type NavItem = {
  label: string;
  labelKey?: string;
  href?: string;
  icon: LucideIcon;
  roles: Role[];
  permission?: string;
  permissionsAny?: string[];
  children?: NavItem[];
};
export const navigation: NavItem[] = [
  {
    label: "الرئيسية",
    labelKey: "nav.dashboard",
    href: "/dashboard",
    icon: LayoutDashboard,
    roles: ["admin", "member", "accountant"],
  },
  {
    label: "الموارد البشرية",
    labelKey: "nav.hr",
    icon: BriefcaseBusiness,
    roles: ["admin", "member"],
    children: [
      {
        label: "جميع الإداريين والمناديب",
        labelKey: "nav.employees",
        href: "/dashboard/employees",
        icon: Users,
        roles: ["admin", "member"],
        permission: "employees.read",
      },
      {
        label: "كتالوجات الموظفين",
        labelKey: "nav.catalogs",
        href: "/dashboard/hr/catalogs",
        icon: BriefcaseBusiness,
        roles: ["admin", "member"],
        permissionsAny: [
          "employees.read",
          "residency.read",
          "licenses.read",
          "sponsors.read",
          "operating_cities.read",
        ],
      },
      {
        label: "وثائق الموظفين والمناديب",
        labelKey: "nav.documents",
        href: "/dashboard/hr/documents",
        icon: FileText,
        roles: ["admin", "member"],
        permission: "documents.read",
      },
      {
        label: "التأمين الطبي",
        labelKey: "nav.insurance",
        href: "/dashboard/hr/insurance",
        icon: ShieldCheck,
        roles: ["admin", "member"],
        permission: "insurance.read",
      },
      {
        label: "التأمينات الاجتماعية",
        labelKey: "nav.socialInsurance",
        href: "/dashboard/hr/payroll-employees",
        icon: Building2,
        roles: ["admin", "member"],
        permission: "employees.read",
      },
      {
        label: "حالات الغياب",
        labelKey: "nav.absenceCases",
        href: "/dashboard/hr/absence-cases",
        icon: ClipboardList,
        roles: ["admin", "member"],
        permission: "absence_cases.read",
      },
      {
        label: "طلبات تغيير الحالة",
        labelKey: "nav.statusChangeRequests",
        href: "/dashboard/hr/employee-status-change-requests",
        icon: ClipboardList,
        roles: ["admin", "member"],
        permission: "employee_status_changes.read",
      },
      {
        label: "نماذج الموارد البشرية",
        labelKey: "nav.hrForms",
        href: "/dashboard/hr/forms",
        icon: FileText,
        roles: ["admin", "member"],
        permission: "employees.read",
      },
      {
        label: "تنبيهات الوثائق",
        labelKey: "nav.expiryCompliance",
        href: "/dashboard/hr/compliance-expiries",
        icon: ShieldAlert,
        roles: ["admin", "member"],
        permission: "employees.read",
      },
      {
        label: "المناديب الخارجيين",
        labelKey: "nav.externalRiders",
        href: "/dashboard/hr/external-riders",
        icon: Users,
        roles: ["admin", "member"],
        permission: "riders.read",
      },
    ],
  },
  {
    label: "إدارة السكن",
    labelKey: "nav.housing",
    icon: House,
    roles: ["admin", "member"],
    children: [
      {
        label: "السكن",
        labelKey: "nav.housing",
        href: "/dashboard/housing",
        icon: House,
        roles: ["admin", "member"],
        permission: "housing.read",
      },
    ],
  },
  {
    label: "إدارة المنصات",
    labelKey: "nav.platforms",
    icon: Layers,
    roles: ["admin", "member"],
    permissionsAny: ["platform_accounts.read", "platform_assignments.read"],
    children: [
      {
        label: "المنصات",
        labelKey: "nav.platformList",
        href: "/dashboard/platforms",
        icon: Layers,
        roles: ["admin", "member"],
        permission: "platform_accounts.read",
      },
      {
        label: "حسابات المنصات",
        labelKey: "nav.platformAccounts",
        href: "/dashboard/platforms/accounts",
        icon: Server,
        roles: ["admin", "member"],
        permission: "platform_accounts.read",
      },
      {
        label: "سجل العمل للمندوب",
        labelKey: "nav.riderPlatformHistory",
        href: "/dashboard/platforms/rider-history",
        icon: History,
        roles: ["admin", "member"],
        permission: "platform_assignments.read",
      },
    ],
  },
  {
    label: "إدارة الأسطول والمركبات",
    labelKey: "nav.fleet",
    icon: Car,
    roles: ["admin", "member"],
    permissionsAny: [
      "fleet.vehicles.read",
      "fleet.assignments.read",
      "fleet.issues.read",
      "fleet.accidents.read",
      "fleet.compliance.read",
      "fleet.daily_distances.read",
      "fuel.read",
      "fuel.manage",
      "fuel.import",
    ],
    children: [
      {
        label: "المركبات",
        labelKey: "nav.vehicles",
        href: "/dashboard/fleet/vehicles",
        icon: Car,
        roles: ["admin", "member"],
        permission: "fleet.vehicles.read",
      },
      {
        label: "بطاقات الوقود",
        labelKey: "nav.fuelCards",
        href: "/dashboard/fleet/fuel-cards",
        icon: Fuel,
        roles: ["admin", "member"],
        permissionsAny: ["fuel.read", "fuel.manage", "fuel.import"],
      },
      {
        label: "التعيينات والاستلام",
        labelKey: "nav.vehicleAssignments",
        href: "/dashboard/fleet/assignments",
        icon: Key,
        roles: ["admin", "member"],
        permission: "fleet.assignments.read",
      },
      {
        label: "المسافات اليومية (GPS والعداد)",
        labelKey: "nav.vehicleDailyDistances",
        href: "/dashboard/fleet/daily-distances",
        icon: Gauge,
        roles: ["admin", "member"],
        permissionsAny: ["fleet.daily_distances.read", "fleet.vehicles.read", "fleet.assignments.read"],
      },
      {
        label: "الأعطال والمشاكل",
        labelKey: "nav.vehicleIssues",
        href: "/dashboard/fleet/issues",
        icon: Wrench,
        roles: ["admin", "member"],
        permission: "fleet.issues.read",
      },
      {
        label: "الحوادث والتقارير",
        labelKey: "nav.vehicleAccidents",
        href: "/dashboard/fleet/accidents",
        icon: AlertTriangle,
        roles: ["admin", "member"],
        permission: "fleet.accidents.read",
      },
      {
        label: "متابعة تجديد التراخيص",
        labelKey: "nav.vehicleCompliance",
        href: "/dashboard/fleet/compliance",
        icon: ShieldCheck,
        roles: ["admin", "member"],
        permission: "fleet.compliance.read",
      },
      {
        label: "الكتالوجات والموردون",
        labelKey: "nav.vehicleCatalogs",
        href: "/dashboard/fleet/catalogs",
        icon: BookOpen,
        roles: ["admin", "member"],
        permission: "fleet.vehicles.read",
      },
    ],
  },
  {
    label: "ربط المركبات بالمنصات",
    labelKey: "nav.vehicleAccountAssignments",
    icon: Server,
    roles: ["admin", "member"],
    permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
    children: [
      {
        label: "جميع الربطات النشطة",
        href: "/dashboard/fleet/vehicle-account-assignments",
        icon: Server,
        roles: ["admin", "member"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "طلبات التبديل المعلقة",
        href: "/dashboard/fleet/vehicle-account-assignments/switches",
        icon: Repeat,
        roles: ["admin", "member"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "التحذيرات التشغيلية",
        href: "/dashboard/fleet/vehicle-account-assignments/problems",
        icon: AlertTriangle,
        roles: ["admin", "member"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
      {
        label: "عقود تأجير الكفلاء (كيتا)",
        labelKey: "nav.sponsorVehicleLeases",
        href: "/dashboard/fleet/vehicle-account-assignments/leases",
        icon: FileText,
        roles: ["admin", "member"],
        permissionsAny: ["fleet.assignments.read", "fleet.vehicles.read"],
      },
    ],
  },
  {
    label: "إدارة شرائح الاتصال (SIM)",
    labelKey: "nav.phoneSimsGroup",
    icon: Smartphone,
    roles: ["admin", "member"],
    permission: "phone_sims.read",
    children: [
      {
        label: "جميع الشرائح والمخزون",
        labelKey: "nav.phoneSimsAll",
        href: "/dashboard/fleet/phone-sims",
        icon: Smartphone,
        roles: ["admin", "member"],
        permission: "phone_sims.read",
      },
      {
        label: "تعيينات المناديب والعهد",
        labelKey: "nav.phoneSimsAssignments",
        href: "/dashboard/fleet/phone-sims/assignments",
        icon: UserCheck,
        roles: ["admin", "member"],
        permission: "phone_sims.read",
      },
      {
        label: "سجل نقل المسؤوليات",
        labelKey: "nav.phoneSimsTransfers",
        href: "/dashboard/fleet/phone-sims/transfers",
        icon: ArrowLeftRight,
        roles: ["admin", "member"],
        permission: "phone_sims.read",
      },
      {
        label: "الشرائح المعلقة والمؤرشفة",
        labelKey: "nav.phoneSimsArchived",
        href: "/dashboard/fleet/phone-sims/archived",
        icon: Archive,
        roles: ["admin", "member"],
        permission: "phone_sims.read",
      },
    ],
  },
  {
    label: "إدارة المستخدمين",
    labelKey: "nav.userManagement",
    icon: ShieldCheck,
    roles: ["admin"],
    children: [
      {
        label: "المستخدمون",
        labelKey: "nav.users",
        href: "/dashboard/users",
        icon: Users,
        roles: ["admin"],
        permission: "users.read",
      },
      {
        label: "الأدوار",
        labelKey: "nav.roles",
        href: "/dashboard/users/roles",
        icon: ShieldCheck,
        roles: ["admin"],
        permission: "roles.read",
      },
    ],
  },
  {
    label: "ملفي الشخصي",
    labelKey: "nav.profile",
    href: "/dashboard/profile",
    icon: CircleUserRound,
    roles: ["admin", "member", "accountant"],
  },
];
